### ISSUE TITLE
Wrong flags for ZGC

### ISSUE THREAD

**Issue by roro1506HD** [Oli-idk/EasyMC#112]
As seen [here](https://github.com/LuminescentDev/SimplyMC/blob/v3/src/data/flags.ts#L175), the flags for the ZGC Garbage Collector are the same as the Shenandoah's ones

**Comment by bwmp** [comment]
this is fixed in the latest dev version it just hasn't been pushed to the main repo

**Comment by roro1506HD** [comment]
Oh right, didn't check that branch. Sorry!

**Comment by bwmp** [comment]
@roro1506HD fixed with latest push
