### ISSUE TITLE
Website translation not working properly

### ISSUE THREAD

**Issue by jhqwqmc** [Oli-idk/EasyMC#119]
Some translations of the website will be forcibly replaced with English

**Comment by bwmp** [comment]
this is due to the fact that some languages aren't full translated

**Comment by jhqwqmc** [comment]
He can show the translated language and then it becomes English again

**Comment by saboooor** [comment]
what language is it

**Comment by jhqwqmc** [comment]
> what language is it

The test found that this problem exists in all languages except English.

**Comment by saboooor** [comment]
are your cookies blocked?

**Comment by jhqwqmc** [comment]
No

**Comment by jhqwqmc** [comment]
https://github.com/LuminescentDev/SimplyMC/assets/113768629/262e5420-3111-4cc8-a554-0b9d52604f92

**Comment by saboooor** [comment]
this should be fixed now

**Comment by jhqwqmc** [comment]
It doesn't seem to be perfect. You need to switch the language again every time you operate.

**Comment by bwmp** [comment]
This is ACTUALLY fixed now
