### ISSUE TITLE
[Feature request] Add URL parameters for different options

### ISSUE THREAD

**Issue by AutonomousCat** [Oli-idk/EasyMC#124]
For example:
`https://www.simplymc.art/gradients?format=2`
would automatically set this
![image](https://github.com/LuminescentDev/SimplyMC/assets/130127508/04a0e03d-2038-4894-8d72-b18140255295)

Use case:
This would be helpful for my server with a nickname plugin that only supports `<...>` color codes, since I link them to that site when someone asks how to color their name.

**Comment by saboooor** [comment]
so something like presets, but as a link instead of json data?

**Comment by AutonomousCat** [comment]
I didn't realize that was a thing, but yeah that'd work

**Comment by bwmp** [comment]
https://www.birdflop.com/resources/rgb/?format=%3C%23%241%242%243%244%245%246%3E%24f%24c&formatchar=%26 You can now use URL parameters too. the link above should be exactly what you're wanting
