### ISSUE TITLE
Server Software extra flags not being included

### ISSUE THREAD

**Issue by DivannKokos** [Oli-idk/EasyMC#126]
either i'm dumb, either server software do not actually change anything
so... if it doesn't matter for flags generator, then why this choice is exist anyway?
i've just compared choosing different software, and i think they all have same results

**Comment by bwmp** [comment]
purpur has extra flags compared to paper. Also the idea is to have the ability to download a zip file with the server jar and startup file in one but that hasn't been implemented yet.

**Comment by DivannKokos** [comment]
paper `java -Xms4096M -Xmx4096M -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+UseVectorCmov -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:ThreadPriorityPolicy=1 -XX:AllocatePrefetchStyle=3 -XX:+UseZGC -XX:AllocatePrefetchStyle=1 -XX:-ZProactive -jar server.jar --nogui`

purpur `java -Xms4096M -Xmx4096M -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+UseVectorCmov -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:ThreadPriorityPolicy=1 -XX:AllocatePrefetchStyle=3 -XX:+UseZGC -XX:AllocatePrefetchStyle=1 -XX:-ZProactive -jar server.jar --nogui`

i don't see a difference
i've also tried to selecting other flag set but there is no difference either

**Comment by bwmp** [comment]
This actually seems to be a bug where the extra flags arent being added

**Comment by bwmp** [comment]
This has been fixed, when available you can now select the extra flags!
