### ISSUE TITLE
Export only one resource

### ISSUE THREAD

**Issue by scorninpc** [Oli-idk/EasyMC#164]
is it possible to export only RGB resource? i'm trying hard to do that, but as i'm not familiar with node, i'm paining

Any advice or it's impossible?

**Comment by bwmp** [comment]
its possible but unless you're using the exact same web framework as us and copy everything related over its wont work. its not a very easy process and we wont provide support if you decide to do this. Please also mind if you're using our rgb generator code in a closed source/private project you must follow the CSS_LICENSE.md.

**Comment by scorninpc** [comment]
no problems regarding the license, and we have no intention of closing our project

our biggest problem is that we don't use a host with node support, so I'm trying to build statically

but ok about support, i can understand why
