### ISSUE TITLE
Spark analyzer is broken

### ISSUE THREAD

**Issue by GeekCornerGH** [Oli-idk/EasyMC#167]
Prerequistes:
- A Minecraft server running Purpur
- A spark profile to analyze

How to reproduce:
1. Open the profile analyzer
2. Put in a spark profile link (tested against [this one](https://spark.lucko.me/2zjAbLZK3N)
3. Submit it
4. The analyzer will say that the profile analyzing is not available on Paper

**Comment by bwmp** [comment]
Just pushed an update that should fix this sorry for the wait!
