### ISSUE TITLE
[Suggestion] Support <#RRGGBB> formats

### ISSUE THREAD

**Issue by HexedHero** [Oli-idk/EasyMC#22]
A bunch of plugins including my own use the <#RRGGBB> format for hex colors. I thought it'll be nice and a simple update to add since it's just a copy of the default chat with < and > added and the & removed.

**Comment by Oli-idk** [comment]
Were you looking for something like this?
![image](https://user-images.githubusercontent.com/67001116/123173957-4242e400-d434-11eb-8df3-c7fa8c356210.png)

**Comment by HexedHero** [comment]
That is exactly what I was looking for!

**Comment by Oli-idk** [comment]
ok its been pushed should be updated within a couple minutes!
