### ISSUE TITLE
Incorrect hex colors

### ISSUE THREAD

**Issue by HexedHero** [Oli-idk/EasyMC#24]
If you use **3 colors** then make the **1st and 3rd #FF0000** and the **2nd #FFFFFF** and put the text to **12345** it'll output
**<#ff6666>1<#ffcccc>2<#ffffff>3<#ff9999>4<#ff3232>5** - The last 2 hex colors should be the same as the first two since its the exact same color but they are not.

**Comment by Oli-idk** [comment]
that is a problem im aware of but cant quite figure out how to fix😅
