### ISSUE TITLE
Minimessage Formatting

### ISSUE THREAD

**Issue by The-Epic** [Oli-idk/EasyMC#86]
When having colour mode in <#rrggbb> all of the formatting should also get changed to minimessage formatting <bold> <italic> etcetc

**Comment by bwmp** [comment]
the <#rrggbb> isn't specifically a mini message format, mini message also has its own gradient generator which you can find here https://docs.advntr.dev/minimessage/format.html#gradient making this tool kinda useless if mini message is already available.

**Comment by The-Epic** [comment]
Even though they have their own, there are still use cases for this and it would be better to add a toggle or a full minimessage mode if eg a plugin updates to only use minimessage format no longer accepting & codes for text formatting

**Comment by bwmp** [comment]
mind giving me an example of a use case where this tool is needed

**Comment by The-Epic** [comment]
Essentials (i think) is updating to use minimessage formatting, most paper plugins made only for paper wouldnt work with & codes, loads of custom plugins probably now use minimessage formatting so all the & codes wouldnt work

**Comment by bwmp** [comment]
yes but what is a use case where you can't just use mini messages formatting and you need this site is what i'm asking

**Comment by The-Epic** [comment]
Its not just for me, most server owners wouldnt understand half the docs sent out by paper they would use what they would have used prior to any updates to plugins, you could even just add a minimessage "mode" so to say that would just give them the <gradient:hex1:hex2> and the bold so they could attempt to understand it better

**Comment by OakLoaf** [comment]
I actually would be keen to see this added, I personally use the website to be able to visualise hex gradients and then I'll just copy the hex values into MiniMessage format of <gradient:#111111:#222222>

Adding the format to the hex generator would just save a little bit of time and allow for the nice visuals of the website :)

**Comment by bwmp** [comment]
> I actually would be keen to see this added, I personally use the website to be able to visualise hex gradients and then I'll just copy the hex values into MiniMessage format of gradient:#111111:#222222
> 
> Adding the format to the hex generator would just save a little bit of time and allow for the nice visuals of the website :)

I'll look into adding it but if it isnt some simple addition it will not be added. the main issue is currently the entire gradient generation system is coded to work one way and given the way minimessage gradients are used it probably would require a recode of the system

**Comment by bwmp** [comment]
https://d0fe9778.simplymc.pages.dev/gradients/ take a look at this and tell me if its what you're wanting

**Comment by OakLoaf** [comment]
The output doesn't appear to be updating

**Comment by bwmp** [comment]
![image](https://github.com/LuminescentDev/SimplyMC/assets/67001116/ea7e3b3e-13f7-4ae9-b773-4c92023dd67e)
seems to update fine for me are there any errors in console?

**Comment by OakLoaf** [comment]
"Failed to load resource: net::ERR_BLOCKED_BY_CLIENT"

**Comment by bwmp** [comment]
> "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT"

that error is unrelated

**Comment by OakLoaf** [comment]
That's the only error I got, so thought I ought to mention it :)

**Comment by OakLoaf** [comment]
Same issue in a new private session
![image](https://github.com/LuminescentDev/SimplyMC/assets/55620516/49f50c93-d329-40f6-8c00-3a4cad5a4ca4)

**Comment by bwmp** [comment]
could you try clearing your cache and testing again?

**Comment by OakLoaf** [comment]
I just tried on my phone and it worked fine :)

**Comment by bwmp** [comment]
Will be implemented in next update
